### ISSUE TITLE
Add fallback profile image

### ISSUE THREAD

**Issue by ErikBoesen** [apc-gmhs/seniormap#14]

**Comment by JonathanOppenheimer** [comment]
For example 
![c4](https://user-images.githubusercontent.com/12973114/111243332-48c0f480-85d7-11eb-969c-c34a8c1cdd94.PNG)

The best course of action imo would be to just make a little default grey person avatar like yt comments of the same proportions of standard portraits

**Comment by ErikBoesen** [comment]
I agree.
