### ISSUE TITLE
Fix aggressive coloring of native administration areas

### ISSUE THREAD

**Issue by ErikBoesen** [apc-gmhs/seniormap#16]

**Comment by JonathanOppenheimer** [comment]
Turns out andrew knows what this - map will color Indian reservations super harshly which kinda contrasts with the text -- def able to be toned down with the google map tools 
![20210315_221351](https://user-images.githubusercontent.com/12973114/111245987-eae2db80-85db-11eb-9ac9-3effaabb2386.jpg)

**Comment by ErikBoesen** [comment]
Yeah, that's indeed what I meant with this issue. I think the problem is that it uses the `administrative` color defined in the Google Maps JS config.

**Comment by AndrewLester** [comment]
I wonder if we can make campuses turn red instead.
