### ISSUE TITLE
Add marker for home high school

### ISSUE THREAD

**Issue by ErikBoesen** [apc-gmhs/seniormap#24]

**Comment by JonathanOppenheimer** [comment]
Messed around with this and Andrew and I thought it looked kinda bad/not very useful so I'm going to close this
![image 1](https://user-images.githubusercontent.com/12973114/114279999-4d759e80-9a05-11eb-8161-6939d93177dd.png)
![image 2](https://user-images.githubusercontent.com/12973114/114280003-50708f00-9a05-11eb-9e2c-38c9558d869b.PNG)

if for some deranged reason you wanted to use the incredibly shitty code for statics pins i wrote you can peep here 
https://gist.github.com/TheBlueness/62deb0ce302f385db49a85b0cbfcbc23
