### ISSUE TITLE
Conform to ADA

### ISSUE THREAD

**Issue by ErikBoesen** [apc-gmhs/seniormap#4]

**Comment by JonathanOppenheimer** [comment]
by my reading of the ADA stuff the senior map already meets 'Level A' and levels AA and AAA would be incredibly time-consuming to implement (no more text justification, allow the user to choose their own colors for all aspects of the page, etc) and the school club doesn't have to meet the standards anyway. not to malign accessibility however, i think specific items to improve the usability of the site to those with disabilities should be raised and subsequently addressed

**Comment by ErikBoesen** [comment]
@TheBlueness I think when I created this issue we didn't have any alt attributes and things like that. We've largely fixed those issues, so I think we're all good. Thanks for the backlog cleanup.
